### PR TITLE
Fr0 182 refactor external pages

### PR DESCRIPTION
**Pull request by Sam-intellect**
Support
Term
Privacy
All this pages have been refactor

### CODE REVIEW

**Comment by tobiezele** [comment]
@Sam-intellect .jsx in your codes?

**Comment by mysticwillz** [comment]
resolve conflicts

**Comment by Beyond-Logic** [comment]
@Sam-intellect please resolve conflicts . Thanks

**Comment by Sam-intellect** [comment]
It showing on my side that theres no conflict. But am working on it now

**Pull request closed without merging**
